version: '3.8'

services:
  fastapi:
    image: algorithm-llm-audio-fastapi
    container_name: algorithm-llm-audio-fastapi
    ports:
      - "8000:8000"
      - "8001:8001"
    deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]
    environment:
      - FASTAPI_ENV=production
    depends_on:
      - websocket
