version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=production
    depends_on:
      - websocket

  websocket:
    build: .
    command: ["python3", "-m", "Service.main"]  # Run the main.py to start the WebSocket service
    ports:
      - "8001:8001"
